export const adminModuleDefinitions = [
  {
    key: "config_users",
    label: "Usuarios",
    description: "Gestiona cuentas, roles y accesos.",
    path: "/admin/configuracion/usuarios",
    group: "Configuracion",
  },
  {
    key: "config_business",
    label: "Configuracion negocio",
    description: "Moneda, marca y color principal del sistema.",
    path: "/admin/configuracion/negocio",
    group: "Configuracion",
  },
  {
    key: "config_permissions",
    label: "Control de modulos",
    description: "Define que modulos puede ver y abrir cada usuario.",
    path: "/admin/configuracion/permisos",
    group: "Configuracion",
  },
  {
    key: "config_whatsapp",
    label: "Configuracion WhatsApp",
    description: "Configura Evolution API y parametros globales de WhatsApp.",
    path: "/admin/configuracion/whatsapp",
    group: "Configuracion",
  },
  {
    key: "products",
    label: "Productos",
    description: "Catalogo, creacion y edicion de productos.",
    path: "/admin/productos",
    group: "Catalogo",
  },
  {
    key: "categories",
    label: "Categorias",
    description: "Gestiona categorias del catalogo.",
    path: "/admin/categorias",
    group: "Catalogo",
  },
  {
    key: "suppliers",
    label: "Proveedores",
    description: "Gestiona proveedores del catalogo.",
    path: "/admin/proveedores",
    group: "Catalogo",
  },
  {
    key: "quotes",
    label: "Cotizaciones",
    description: "Crea, edita y consulta cotizaciones.",
    path: "/admin/cotizaciones",
    group: "Comercial",
  },
  {
    key: "chats",
    label: "Chats",
    description: "Bandeja unificada de conversaciones y automatizaciones.",
    path: "/cliente/chats",
    group: "Cliente",
  },
  {
    key: "contacts",
    label: "Contactos",
    description: "Base de contactos y seguimiento comercial.",
    path: "/cliente/contactos",
    group: "Cliente",
  },
  {
    key: "crm",
    label: "CRM",
    description: "Pipeline y gestion de oportunidades.",
    path: "/cliente/crm",
    group: "Cliente",
  },
  {
    key: "flows",
    label: "Flujos",
    description: "Automatizaciones y respuestas estructuradas.",
    path: "/cliente/flujos",
    group: "Cliente",
  },
  {
    key: "seguimientos",
    label: "Seguimientos",
    description: "Reglas y seguimientos automaticos por contacto.",
    path: "/cliente/seguimientos",
    group: "Cliente",
  },
  {
    key: "marketing_ia",
    label: "Marketing IA",
    description: "Campanas, mensajes y activaciones inteligentes.",
    path: "/cliente/marketing-ia",
    group: "Cliente",
  },
  {
    key: "finanzas",
    label: "Finanzas",
    description: "Seguimiento de ingresos, egresos y control financiero.",
    path: "/cliente/finanzas",
    group: "Cliente",
  },
  {
    key: "connection",
    label: "Conexion",
    description: "Gestion de canales y vinculos de WhatsApp.",
    path: "/cliente/conexion",
    group: "Cliente",
  },
  {
    key: "agents",
    label: "Agentes",
    description: "Configuracion y estudio de agentes.",
    path: "/cliente/agentes",
    group: "Cliente",
  },
  {
    key: "client_official_api",
    label: "Api oficial (Cliente)",
    description: "Permite ver y operar el modulo Api oficial en el area cliente.",
    path: "/cliente/api-oficial",
    group: "Cliente",
  },
] as const;

export type AdminModuleKey = (typeof adminModuleDefinitions)[number]["key"];
