import type { ComponentType } from "react";
import {
  CarFront,
  Clock3,
  Coffee,
  Flag,
  Flower2,
  Grid2x2,
  Lightbulb,
  Shapes,
  Smile,
  Users,
} from "lucide-react";

export const CHAT_COMPOSER_RECENT_KEY = "shared-inbox:composer-recent-emojis";

export type ComposerEmojiCategory =
  | "caras"
  | "personas"
  | "naturaleza"
  | "comida"
  | "viajes"
  | "objetos"
  | "simbolos"
  | "banderas";

export type ComposerEmoji = {
  emoji: string;
  label: string;
  category: ComposerEmojiCategory;
  keywords: string[];
};

export const CHAT_COMPOSER_EMOJI_GROUPS: Record<ComposerEmojiCategory, ComposerEmoji[]> = {
  caras: [
    { emoji: "😀", label: "sonrisa", category: "caras", keywords: ["feliz", "alegre"] },
    { emoji: "😁", label: "sonrisa abierta", category: "caras", keywords: ["feliz", "dientes"] },
    { emoji: "😂", label: "risa", category: "caras", keywords: ["feliz", "broma"] },
    { emoji: "🤣", label: "carcajada", category: "caras", keywords: ["risa", "broma"] },
    { emoji: "😃", label: "alegría", category: "caras", keywords: ["feliz"] },
    { emoji: "😄", label: "entusiasmo", category: "caras", keywords: ["feliz", "energía"] },
    { emoji: "😅", label: "alivio", category: "caras", keywords: ["nervios", "sudor"] },
    { emoji: "😆", label: "diversión", category: "caras", keywords: ["risa"] },
    { emoji: "😉", label: "guiño", category: "caras", keywords: ["cómplice"] },
    { emoji: "😊", label: "amabilidad", category: "caras", keywords: ["sonrisa"] },
    { emoji: "🙂", label: "tranquilo", category: "caras", keywords: ["sereno"] },
    { emoji: "🙃", label: "irónico", category: "caras", keywords: ["broma"] },
    { emoji: "😍", label: "amor", category: "caras", keywords: ["corazones"] },
    { emoji: "🥰", label: "cariño", category: "caras", keywords: ["afecto"] },
    { emoji: "😘", label: "beso", category: "caras", keywords: ["amor"] },
    { emoji: "😗", label: "beso suave", category: "caras", keywords: ["amor"] },
    { emoji: "😜", label: "pícara", category: "caras", keywords: ["broma"] },
    { emoji: "🤪", label: "locura", category: "caras", keywords: ["broma"] },
    { emoji: "🤗", label: "abrazo", category: "caras", keywords: ["cariño"] },
    { emoji: "🤭", label: "sorpresa", category: "caras", keywords: ["vergüenza"] },
    { emoji: "🤔", label: "pensativo", category: "caras", keywords: ["duda"] },
    { emoji: "🤨", label: "escéptico", category: "caras", keywords: ["duda"] },
    { emoji: "😐", label: "neutral", category: "caras", keywords: ["serio"] },
    { emoji: "😑", label: "sin reacción", category: "caras", keywords: ["serio"] },
    { emoji: "😶", label: "silencio", category: "caras", keywords: ["callado"] },
    { emoji: "😏", label: "sarcástico", category: "caras", keywords: ["guiño"] },
    { emoji: "🙄", label: "desagrado", category: "caras", keywords: ["ojos"] },
    { emoji: "😌", label: "alivio", category: "caras", keywords: ["calma"] },
    { emoji: "😔", label: "triste", category: "caras", keywords: ["pena"] },
    { emoji: "😴", label: "sueño", category: "caras", keywords: ["cansancio"] },
    { emoji: "😎", label: "confianza", category: "caras", keywords: ["cool"] },
    { emoji: "😭", label: "llanto", category: "caras", keywords: ["triste", "lágrimas"] },
  ],
  personas: [
    { emoji: "👋", label: "saludo", category: "personas", keywords: ["hola"] },
    { emoji: "✋", label: "alto", category: "personas", keywords: ["espera"] },
    { emoji: "👌", label: "ok", category: "personas", keywords: ["bien"] },
    { emoji: "🤌", label: "énfasis", category: "personas", keywords: ["italiano"] },
    { emoji: "🤞", label: "suerte", category: "personas", keywords: ["deseo"] },
    { emoji: "🤟", label: "te quiero", category: "personas", keywords: ["amor"] },
    { emoji: "🤘", label: "rock", category: "personas", keywords: ["música"] },
    { emoji: "🤙", label: "llámame", category: "personas", keywords: ["teléfono"] },
    { emoji: "👍", label: "aprobación", category: "personas", keywords: ["bien"] },
    { emoji: "👎", label: "desaprobación", category: "personas", keywords: ["no"] },
    { emoji: "👏", label: "aplauso", category: "personas", keywords: ["felicitación"] },
    { emoji: "🙌", label: "celebración", category: "personas", keywords: ["fiesta"] },
    { emoji: "👐", label: "abierto", category: "personas", keywords: ["recibir"] },
    { emoji: "🤲", label: "ofrecer", category: "personas", keywords: ["ayuda"] },
    { emoji: "🙏", label: "gracias", category: "personas", keywords: ["oración"] },
    { emoji: "💪", label: "fuerza", category: "personas", keywords: ["poder"] },
    { emoji: "🫶", label: "afecto", category: "personas", keywords: ["amor"] },
    { emoji: "🤝", label: "acuerdo", category: "personas", keywords: ["trato"] },
    { emoji: "🫂", label: "abrazo", category: "personas", keywords: ["cariño"] },
    { emoji: "💃", label: "baile", category: "personas", keywords: ["fiesta"] },
    { emoji: "🕺", label: "baile", category: "personas", keywords: ["fiesta"] },
    { emoji: "🚶", label: "caminar", category: "personas", keywords: ["andar"] },
    { emoji: "🏃", label: "correr", category: "personas", keywords: ["rápido"] },
    { emoji: "🧠", label: "mente", category: "personas", keywords: ["idea"] },
  ],
  naturaleza: [
    { emoji: "🌞", label: "sol", category: "naturaleza", keywords: ["día"] },
    { emoji: "🌝", label: "luna llena", category: "naturaleza", keywords: ["noche"] },
    { emoji: "🌙", label: "luna", category: "naturaleza", keywords: ["noche"] },
    { emoji: "⭐", label: "estrella", category: "naturaleza", keywords: ["brillo"] },
    { emoji: "✨", label: "destello", category: "naturaleza", keywords: ["brillo"] },
    { emoji: "⚡", label: "energía", category: "naturaleza", keywords: ["rápido"] },
    { emoji: "🔥", label: "fuego", category: "naturaleza", keywords: ["intenso"] },
    { emoji: "🌈", label: "arcoíris", category: "naturaleza", keywords: ["colores"] },
    { emoji: "☁️", label: "nube", category: "naturaleza", keywords: ["cielo"] },
    { emoji: "🌧️", label: "lluvia", category: "naturaleza", keywords: ["agua"] },
    { emoji: "⛈️", label: "tormenta", category: "naturaleza", keywords: ["lluvia"] },
    { emoji: "❄️", label: "nieve", category: "naturaleza", keywords: ["frío"] },
    { emoji: "🌊", label: "ola", category: "naturaleza", keywords: ["mar"] },
    { emoji: "🌷", label: "tulipán", category: "naturaleza", keywords: ["flor"] },
    { emoji: "🌹", label: "rosa", category: "naturaleza", keywords: ["flor", "amor"] },
    { emoji: "🌸", label: "flor", category: "naturaleza", keywords: ["primavera"] },
    { emoji: "🌻", label: "girasol", category: "naturaleza", keywords: ["flor"] },
    { emoji: "🍀", label: "suerte", category: "naturaleza", keywords: ["trébol"] },
    { emoji: "🌴", label: "palmera", category: "naturaleza", keywords: ["playa"] },
    { emoji: "🌵", label: "cactus", category: "naturaleza", keywords: ["desierto"] },
    { emoji: "🐶", label: "perro", category: "naturaleza", keywords: ["mascota"] },
    { emoji: "🐱", label: "gato", category: "naturaleza", keywords: ["mascota"] },
    { emoji: "🐻", label: "oso", category: "naturaleza", keywords: ["animal"] },
    { emoji: "🦁", label: "león", category: "naturaleza", keywords: ["animal"] },
    { emoji: "🦋", label: "mariposa", category: "naturaleza", keywords: ["animal"] },
  ],
  comida: [
    { emoji: "🍏", label: "manzana verde", category: "comida", keywords: ["fruta"] },
    { emoji: "🍎", label: "manzana", category: "comida", keywords: ["fruta"] },
    { emoji: "🍌", label: "banano", category: "comida", keywords: ["fruta"] },
    { emoji: "🍉", label: "sandía", category: "comida", keywords: ["fruta"] },
    { emoji: "🍇", label: "uvas", category: "comida", keywords: ["fruta"] },
    { emoji: "🍓", label: "fresa", category: "comida", keywords: ["fruta"] },
    { emoji: "🫐", label: "arándanos", category: "comida", keywords: ["fruta"] },
    { emoji: "🍒", label: "cerezas", category: "comida", keywords: ["fruta"] },
    { emoji: "🍑", label: "durazno", category: "comida", keywords: ["fruta"] },
    { emoji: "🍍", label: "piña", category: "comida", keywords: ["fruta"] },
    { emoji: "🥝", label: "kiwi", category: "comida", keywords: ["fruta"] },
    { emoji: "🍅", label: "tomate", category: "comida", keywords: ["vegetal"] },
    { emoji: "🥑", label: "aguacate", category: "comida", keywords: ["vegetal"] },
    { emoji: "🥕", label: "zanahoria", category: "comida", keywords: ["vegetal"] },
    { emoji: "🌮", label: "taco", category: "comida", keywords: ["mexicano"] },
    { emoji: "🌯", label: "wrap", category: "comida", keywords: ["burrito"] },
    { emoji: "🍔", label: "hamburguesa", category: "comida", keywords: ["comida"] },
    { emoji: "🍟", label: "papas", category: "comida", keywords: ["fritas"] },
    { emoji: "🍕", label: "pizza", category: "comida", keywords: ["italiana"] },
    { emoji: "🍿", label: "crispetas", category: "comida", keywords: ["cine"] },
    { emoji: "🍩", label: "donut", category: "comida", keywords: ["dulce"] },
    { emoji: "🍪", label: "galleta", category: "comida", keywords: ["dulce"] },
    { emoji: "🍰", label: "pastel", category: "comida", keywords: ["torta"] },
    { emoji: "🧁", label: "cupcake", category: "comida", keywords: ["dulce"] },
    { emoji: "☕", label: "café", category: "comida", keywords: ["bebida"] },
    { emoji: "🧃", label: "jugo", category: "comida", keywords: ["bebida"] },
    { emoji: "🥤", label: "refresco", category: "comida", keywords: ["bebida"] },
  ],
  viajes: [
    { emoji: "🚗", label: "auto", category: "viajes", keywords: ["carro"] },
    { emoji: "🚕", label: "taxi", category: "viajes", keywords: ["carro"] },
    { emoji: "🚙", label: "SUV", category: "viajes", keywords: ["carro"] },
    { emoji: "🚌", label: "bus", category: "viajes", keywords: ["transporte"] },
    { emoji: "🚎", label: "trolebús", category: "viajes", keywords: ["transporte"] },
    { emoji: "🛵", label: "moto", category: "viajes", keywords: ["transporte"] },
    { emoji: "🏍️", label: "motocicleta", category: "viajes", keywords: ["transporte"] },
    { emoji: "🚲", label: "bicicleta", category: "viajes", keywords: ["transporte"] },
    { emoji: "✈️", label: "avión", category: "viajes", keywords: ["viaje"] },
    { emoji: "🚀", label: "cohete", category: "viajes", keywords: ["rápido"] },
    { emoji: "🚢", label: "barco", category: "viajes", keywords: ["mar"] },
    { emoji: "🚂", label: "tren", category: "viajes", keywords: ["transporte"] },
    { emoji: "🛫", label: "despegue", category: "viajes", keywords: ["viaje"] },
    { emoji: "🛬", label: "aterrizaje", category: "viajes", keywords: ["viaje"] },
    { emoji: "🗺️", label: "mapa", category: "viajes", keywords: ["ruta"] },
    { emoji: "🏖️", label: "playa", category: "viajes", keywords: ["vacaciones"] },
    { emoji: "🏝️", label: "isla", category: "viajes", keywords: ["vacaciones"] },
    { emoji: "⛰️", label: "montaña", category: "viajes", keywords: ["naturaleza"] },
    { emoji: "🌍", label: "planeta", category: "viajes", keywords: ["mundo"] },
    { emoji: "🌎", label: "mundo", category: "viajes", keywords: ["planeta"] },
    { emoji: "🌏", label: "tierra", category: "viajes", keywords: ["mundo"] },
  ],
  objetos: [
    { emoji: "📱", label: "teléfono", category: "objetos", keywords: ["móvil"] },
    { emoji: "💻", label: "portátil", category: "objetos", keywords: ["computador"] },
    { emoji: "🖥️", label: "escritorio", category: "objetos", keywords: ["computador"] },
    { emoji: "⌚", label: "reloj", category: "objetos", keywords: ["tiempo"] },
    { emoji: "📷", label: "cámara", category: "objetos", keywords: ["foto"] },
    { emoji: "🎥", label: "video", category: "objetos", keywords: ["cámara"] },
    { emoji: "🔊", label: "volumen", category: "objetos", keywords: ["audio"] },
    { emoji: "🔔", label: "notificación", category: "objetos", keywords: ["aviso"] },
    { emoji: "💡", label: "idea", category: "objetos", keywords: ["luz"] },
    { emoji: "🔑", label: "llave", category: "objetos", keywords: ["acceso"] },
    { emoji: "🛒", label: "carrito", category: "objetos", keywords: ["compra"] },
    { emoji: "📦", label: "paquete", category: "objetos", keywords: ["envío"] },
    { emoji: "🎁", label: "regalo", category: "objetos", keywords: ["detalle"] },
    { emoji: "📌", label: "pin", category: "objetos", keywords: ["fijar"] },
    { emoji: "🖊️", label: "bolígrafo", category: "objetos", keywords: ["escribir"] },
    { emoji: "✏️", label: "lápiz", category: "objetos", keywords: ["escribir"] },
    { emoji: "📚", label: "libros", category: "objetos", keywords: ["estudio"] },
    { emoji: "🧸", label: "peluche", category: "objetos", keywords: ["juguete"] },
    { emoji: "🧰", label: "herramientas", category: "objetos", keywords: ["reparar"] },
    { emoji: "🧾", label: "recibo", category: "objetos", keywords: ["factura"] },
    { emoji: "🧭", label: "brújula", category: "objetos", keywords: ["ruta"] },
  ],
  simbolos: [
    { emoji: "❤️", label: "corazón", category: "simbolos", keywords: ["amor"] },
    { emoji: "🧡", label: "corazón naranja", category: "simbolos", keywords: ["amor"] },
    { emoji: "💛", label: "corazón amarillo", category: "simbolos", keywords: ["amor"] },
    { emoji: "💚", label: "corazón verde", category: "simbolos", keywords: ["amor"] },
    { emoji: "💙", label: "corazón azul", category: "simbolos", keywords: ["amor"] },
    { emoji: "💜", label: "corazón morado", category: "simbolos", keywords: ["amor"] },
    { emoji: "🖤", label: "corazón negro", category: "simbolos", keywords: ["amor"] },
    { emoji: "🤍", label: "corazón blanco", category: "simbolos", keywords: ["amor"] },
    { emoji: "💯", label: "cien", category: "simbolos", keywords: ["perfecto"] },
    { emoji: "✅", label: "confirmación", category: "simbolos", keywords: ["ok"] },
    { emoji: "❌", label: "cancelar", category: "simbolos", keywords: ["no"] },
    { emoji: "❓", label: "pregunta", category: "simbolos", keywords: ["duda"] },
    { emoji: "❗", label: "alerta", category: "simbolos", keywords: ["urgente"] },
    { emoji: "➡️", label: "derecha", category: "simbolos", keywords: ["flecha"] },
    { emoji: "⬅️", label: "izquierda", category: "simbolos", keywords: ["flecha"] },
    { emoji: "⬆️", label: "arriba", category: "simbolos", keywords: ["flecha"] },
    { emoji: "⬇️", label: "abajo", category: "simbolos", keywords: ["flecha"] },
    { emoji: "➕", label: "más", category: "simbolos", keywords: ["sumar"] },
    { emoji: "➖", label: "menos", category: "simbolos", keywords: ["restar"] },
    { emoji: "♻️", label: "reciclar", category: "simbolos", keywords: ["repetir"] },
    { emoji: "🚫", label: "prohibido", category: "simbolos", keywords: ["no"] },
  ],
  banderas: [
    { emoji: "🇪🇸", label: "España", category: "banderas", keywords: ["español"] },
    { emoji: "🇲🇽", label: "México", category: "banderas", keywords: ["latam"] },
    { emoji: "🇨🇴", label: "Colombia", category: "banderas", keywords: ["latam"] },
    { emoji: "🇦🇷", label: "Argentina", category: "banderas", keywords: ["latam"] },
    { emoji: "🇨🇱", label: "Chile", category: "banderas", keywords: ["latam"] },
    { emoji: "🇵🇪", label: "Perú", category: "banderas", keywords: ["latam"] },
    { emoji: "🇻🇪", label: "Venezuela", category: "banderas", keywords: ["latam"] },
    { emoji: "🇺🇸", label: "Estados Unidos", category: "banderas", keywords: ["usa"] },
    { emoji: "🇵🇦", label: "Panamá", category: "banderas", keywords: ["latam"] },
    { emoji: "🇪🇨", label: "Ecuador", category: "banderas", keywords: ["latam"] },
    { emoji: "🇩🇴", label: "República Dominicana", category: "banderas", keywords: ["caribe"] },
    { emoji: "🇵🇷", label: "Puerto Rico", category: "banderas", keywords: ["caribe"] },
  ],
};

export const CHAT_COMPOSER_EMOJIS = Object.values(CHAT_COMPOSER_EMOJI_GROUPS).flat();
export const CHAT_COMPOSER_CATEGORY_ORDER: Array<"todos" | ComposerEmojiCategory> = [
  "todos",
  "caras",
  "personas",
  "naturaleza",
  "comida",
  "viajes",
  "objetos",
  "simbolos",
  "banderas",
];
export type ComposerEmojiTab = "todos" | "recientes" | ComposerEmojiCategory;

export const CHAT_COMPOSER_CATEGORY_LABELS: Record<ComposerEmojiTab, string> = {
  todos: "Todos",
  recientes: "Recientes",
  caras: "Caras",
  personas: "Personas",
  naturaleza: "Naturaleza",
  comida: "Comida",
  viajes: "Viajes",
  objetos: "Objetos",
  simbolos: "Símbolos",
  banderas: "Banderas",
};

export const CHAT_COMPOSER_CATEGORY_ICONS: Record<ComposerEmojiTab, ComponentType<{ className?: string }>> = {
  todos: Grid2x2,
  recientes: Clock3,
  caras: Smile,
  personas: Users,
  naturaleza: Flower2,
  comida: Coffee,
  viajes: CarFront,
  objetos: Lightbulb,
  simbolos: Shapes,
  banderas: Flag,
};

export function normalizeComposerEmojiSearch(value: string) {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}
